In [2]:
import numpy as np

#### 1) Consider the following NumPy array
import numpy

Y = numpy.array([ [3,6,9,12], [15,18,21,24], [27,30,33,36], [39,42,45,48], 
[51,54,57,60] ])

i) Return the array of elements in the third column (from all rows).

ii) Return a sub-array comprising of odd rows and even columns of the 
above array

iii) Build a new array from the above array swapping first and last, 
second and third columns

iv) Swap rows and columns in reverse order


In [3]:
Y = np.array([ [3,6,9,12], [15,18,21,24], [27,30,33,36], [39,42,45,48], [51,54,57,60] ])
Y

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [4]:
Y[:, 2]

array([ 9, 21, 33, 45, 57])

In [5]:
newArr = Y[1::2, 0::2]
newArr

array([[15, 21],
       [39, 45]])

In [6]:
newArr = np.array([Y[:,-1], Y[:,2], Y[:,1], Y[:,0]]).T
newArr

array([[12,  9,  6,  3],
       [24, 21, 18, 15],
       [36, 33, 30, 27],
       [48, 45, 42, 39],
       [60, 57, 54, 51]])

In [8]:
# Swap rows and columns in reverse order

newArr = Y[::-1, ::-1]
print(newArr)

[[60 57 54 51]
 [48 45 42 39]
 [36 33 30 27]
 [24 21 18 15]
 [12  9  6  3]]


#### 2) Get all items between 7 and 20 from b.

Input:

b = np.array([13, 6, 11, 19, 10, 3, 27])

Desired Output:

(array([13,11,19,10]),)

In [21]:
b = np.array([13, 6, 11, 19, 10, 3, 27])
b[(b>=7) & (b<=20)]

array([13, 11, 19, 10])

#### 3) Identify the index of 6th repetition of 5 in an array

x = np.array([5, 2, 5, 5, 3, 4, 3, 5, 5, 2, 5, 5, 2])

In [22]:
x = np.array([5, 2, 5, 5, 3, 4, 3, 5, 5, 2, 5, 5, 2])

count = 0
for i, num in enumerate(x):
    if num == 5:
        count += 1
        if count == 6:
            print(i)
            break

10
