### T2: Using Numpy implement Array basic operations


In [21]:
import numpy as np

In [22]:
a = np.array([[5.24, 3.28, 6.99], [3.24, 5.82, 2.39], [2.54, 3.39, 6.39]])
a

array([[5.24, 3.28, 6.99],
       [3.24, 5.82, 2.39],
       [2.54, 3.39, 6.39]])

#### 2) Consider the following NumPy array

import numpy as np

a = np.array([[5.24, 3.28, 6.99], [3.24, 5.82, 2.39], [2.54, 3.39, 6.39]])


i) Identify the sum of all elements, sum of each column and sum of each row of the array a

_Given array:_

[[5.24 3.28 6.99]
<br>
 [3.24 5.82 2.39]
<br>
 [2.54 3.39 6.39]]
<br>

*Sum - elements:*
<br>
39.28
<br>

*Sum - column:*
<br>
[11.02 12.49 15.77]
<br>

*Sum - row:*
<br>
[15.51 11.45 12.32]


In [23]:
print("Sum of elements = " + str(np.sum(a)))
print("Sum of columns = " + str(np.sum(a, axis=0)))
print("Sum of rows = " + str(np.sum(a, axis=1)))

Sum of elements = 39.28
Sum of columns = [11.02 12.49 15.77]
Sum of rows = [15.51 11.45 12.32]


(ii) Substitute all numbers in the above array which is equal, less and greater to a given number

[[5.24 3.28 6.99]
<br>
[3.24 5.82 2.39]
<br>
[2.54 3.39 6.39]]
<br>

Substitute elements of the above array which are equal to 5.32 with 15.32
<br>
[[5.24 3.28 6.99]
<br>
[3.24 5.82 2.39]
<br>
[2.54 3.39 6.39]]
<br>

Substitute elements of the above array which are less than 5.32 with 15.32
<br>
[[15.32 15.32 6.99]
<br>
[15.32 5.82 15.32]
<br>
[15.32 15.32 6.39]]
<br>

Substitute elements of the above array which are greater than 5.32 with 15.32
<br>
[[ 5.24 3.28 15.32]
<br>
[ 3.24 15.32 2.39]
<br>
[ 2.54 3.39 15.32]]

In [27]:
a

array([[5.24, 3.28, 6.99],
       [3.24, 5.82, 2.39],
       [2.54, 3.39, 6.39]])

In [36]:
n = 5.32
sub = 15.32
equal_func = np.vectorize(lambda x: sub if x == n else x)
lower_func = np.vectorize(lambda x: sub if x < n else x)
greater_func = np.vectorize(lambda x: sub if x > n else x)

#apply function to array
result = equal_func(a)
print(f"Substitute elements of the above array which are equal to {n} with {sub}:\n" + str(result))
result = lower_func(a)
print(f"Substitute elements of the above array which are lower than {n} with {sub}:\n" + str(result))
result = greater_func(a)
print(f"Substitute elements of the above array which are greater than {n} with {sub}:\n" + str(result))

Substitute elements of the above array which are equal to 5.32 with 15.32:
[[5.24 3.28 6.99]
 [3.24 5.82 2.39]
 [2.54 3.39 6.39]]
Substitute elements of the above array which are lower than 5.32 with 15.32:
[[15.32 15.32  6.99]
 [15.32  5.82 15.32]
 [15.32 15.32  6.39]]
Substitute elements of the above array which are greater than 5.32 with 15.32:
[[ 5.24  3.28 15.32]
 [ 3.24 15.32  2.39]
 [ 2.54  3.39 15.32]]


iii) Sort row and column in ascending order
<br>
Given array:
<br>
[[5.24 3.28 6.99]
<br>
[3.24 5.82 2.39]
<br>
[2.54 3.39 6.39]]

Sort the above array by row:
<br>
[[3.28 5.24 6.99]
<br>
[2.39 3.24 5.82]
<br>
[2.54 3.39 6.39]]

Sort the above array by column:
<br>
[[2.54 3.28 2.39]
<br>
[3.24 3.39 6.39]
<br>
[5.24 5.82 6.99]]

In [40]:
print("Sorting array by row:\n" + str(np.sort(a, axis=1)))
print("Sorting array by column:\n" + str(np.sort(a, axis=0)))

Sorting array by row:
[[3.28 5.24 6.99]
 [2.39 3.24 5.82]
 [2.54 3.39 6.39]]
Sorting array by column:
[[2.54 3.28 2.39]
 [3.24 3.39 6.39]
 [5.24 5.82 6.99]]


(iv) Split the above array into two arrays along the second axis
<br>
Original array:
<br>
[[ 0 1 2 3]
<br>
[ 4 5 6 7]
<br>
[ 8 9 10 11]
<br>
[12 13 14 15]]

After splitting horizontally:
<br>
[array([[ 0, 1, 2],
<br>
 [ 4, 5, 6],
<br>
 [ 8, 9, 10],
<br>
 [12, 13, 14]]), array([[ 3],
<br>
 [ 7],
<br>
 [11],
<br>
 [15]]), array([], shape=(4, 0), dtype=int64)]

In [57]:
arr = np.arange(16).reshape(4, 4)
print(np.hsplit(arr, [3]))


[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [66]:
arr = np.array([(2+3j), (4-1j), (2-2j), (4-3j), (3+5j)])
np.sort_complex(arr)

array([2.-2.j, 2.+3.j, 3.+5.j, 4.-3.j, 4.-1.j])

#### 3) Construct a program to sort the array on height by assuming an structured array from given set of name, height, class and their data types and . 

Before sorting:
<br>[('John', 6, 52.5 ) ('Naught', 6, 48.5 ) ('Prince', 3, 41.1 ) ('Paul', 4, 43.11)]

After sorting:
<br>[('Prince', 3, 41.1 ) ('Paul', 4, 43.11) ('Naught', 6, 48.5 ) ('John', 6, 52.5 )]

In [93]:
dtype = [('name', 'S10'), ('class', 'int'), ('height', 'float')]
arr = np.array([('John', 6, 52.5 ), ('Naught', 6, 48.5 ), ('Prince', 3, 41.1 ), ('Paul', 4, 43.11)], dtype = [('name', 'S10'), ('class', 'int'), ('height', 'float')])
np.sort(arr, order=['height'])

array([(b'Prince', 3, 41.1 ), (b'Paul', 4, 43.11), (b'Naught', 6, 48.5 ),
       (b'John', 6, 52.5 )],
      dtype=[('name', 'S10'), ('class', '<i4'), ('height', '<f8')])